Fix AttributeError: 'ImageDraw' object has no attribute 'multiline_textsize'
Fixes AttributeError: 'ImageDraw' object has no attribute 'multiline_textsize' when using Pillow >10 trying to do X/Y/Z grids. This specially happens if using Python 3.12, where Pillow 10.1.0 is the least compatible version.

It changes multiline_textsize to multiline_textbbox, returning a tuple (left, top, right, bottom). text_width can be calculated as right - left and text_height as bottom - top.
Also adjust get_font to make it return a valid font object from a given font size.

Draft for now, since stable is using Python 3.10. It can be applied either if updating the Pillow library version in the requirements or if using Python 3.12.


## Checklist:

- [x] I have read [contributing wiki page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing)
- [x] I have performed a self-review of my own code
- [x] My code follows the [style guidelines](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing#code-style)
- [ ] My code passes [tests](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Tests)